// AUTO-GENERATED 追加フレーズ（型×拡張単語）。リスニング/並べ替えの母数を増やす用。
export const EXTRA = {
 "1": [
  "I wanna be a vet.",
  "I wanna be a nurse.",
  "I wanna be a pilot.",
  "I wanna be a doctor.",
  "I wanna be a singer.",
  "I wanna be a YouTuber.",
  "I wanna be a lawyer.",
  "I wanna be an artist.",
  "I wanna be rich.",
  "I wanna be famous.",
  "I wanna be kind.",
  "I wanna be strong.",
  "I wanna be brave.",
  "I wanna be free.",
  "I wanna be healthy.",
  "I wanna be a good cook.",
  "I wanna sleep now.",
  "I wanna eat sushi.",
  "I wanna learn English.",
  "I wanna travel the world.",
  "I wanna buy a car.",
  "I wanna go home.",
  "I wanna take a break.",
  "I wanna watch a movie.",
  "I wanna play games.",
  "I wanna call you.",
  "I wanna study hard.",
  "I wanna save money.",
  "I wanna help you.",
  "I wanna start over.",
  "I'm gonna be a vet.",
  "I'm gonna be a nurse.",
  "I'm gonna be a pilot.",
  "I'm gonna be a doctor.",
  "I'm gonna be a singer.",
  "I'm gonna be a YouTuber.",
  "I'm gonna be a lawyer.",
  "I'm gonna be an artist.",
  "I'm gonna sleep now.",
  "I'm gonna eat sushi.",
  "I'm gonna learn English.",
  "I'm gonna travel the world.",
  "I'm gonna buy a car.",
  "I'm gonna go home.",
  "I'm gonna take a break.",
  "I gotta be a vet.",
  "I gotta be a nurse.",
  "I gotta be a pilot.",
  "I gotta be a doctor.",
  "I gotta be a singer.",
  "I gotta be a YouTuber.",
  "I gotta be a lawyer.",
  "I gotta be an artist.",
  "I gotta sleep now.",
  "I gotta eat sushi.",
  "I gotta learn English.",
  "I gotta travel the world.",
  "I gotta buy a car.",
  "I gotta go home.",
  "I gotta take a break."
 ],
 "2": [
  "How do I say thank you in Japanese?",
  "How do I say sorry in Japanese?",
  "How do I say good morning in Japanese?",
  "How do I say I love you in Japanese?",
  "How do I say cat in Japanese?",
  "How do I say water in Japanese?",
  "How do I say station in Japanese?",
  "How do I say hospital in Japanese?",
  "How do I say delicious in Japanese?",
  "How do I say beautiful in Japanese?",
  "How do I say expensive in Japanese?",
  "How do I say friend in Japanese?",
  "What's the difference between cats and dogs?",
  "What's the difference between tea and coffee?",
  "What's the difference between city and town?",
  "What's the difference between river and lake?",
  "What's the difference between car and bus?",
  "What's the difference between summer and winter?",
  "Could you explain the rule one more time?",
  "Could you explain the question one more time?",
  "Could you explain this word one more time?",
  "Could you explain the schedule one more time?",
  "Could you explain the plan one more time?",
  "Could you explain the story one more time?",
  "How do you use though?",
  "How do you use anyway?",
  "How do you use however?",
  "How do you use by the way?",
  "How do you use actually?",
  "How do you use kind of?"
 ],
 "5": [
  "I think it's true.",
  "I think you're right.",
  "I think it's too expensive.",
  "I think we should go.",
  "I think this is fun.",
  "I think she is kind.",
  "I think it will rain.",
  "I think he is busy.",
  "I guess it's true.",
  "I guess you're right.",
  "I guess it's too expensive.",
  "I guess we should go.",
  "I guess this is fun.",
  "I guess she is kind.",
  "That sounds fun.",
  "That sounds great.",
  "That sounds hard.",
  "That sounds boring.",
  "That sounds delicious.",
  "That sounds dangerous.",
  "That sounds amazing.",
  "That sounds nice.",
  "I would like to order coffee.",
  "I would like to book a room.",
  "I would like to see the menu.",
  "I would like to pay by card.",
  "I would like to check in.",
  "I would like to ask a question.",
  "I would like to make a reservation.",
  "I would like to change my seat."
 ],
 "6": [
  "What do you mean by \"refund\"?",
  "What do you mean by \"deadline\"?",
  "What do you mean by \"discount\"?",
  "What do you mean by \"contract\"?",
  "What do you mean by \"budget\"?",
  "What do you mean by \"invoice\"?",
  "What do you mean by \"warranty\"?",
  "What happened to your car?",
  "What happened to the money?",
  "What happened to your homework?",
  "What happened to the project?",
  "What happened to your cat?",
  "What happened to the party?",
  "What should I do about my visa?",
  "What should I do about this bill?",
  "What should I do about the noise?",
  "What should I do about my cold?",
  "What should I do about this stain?",
  "What should I do about the leak?",
  "What do you wanna drink?",
  "What do you wanna order?",
  "What do you wanna watch?",
  "What do you wanna play?",
  "What do you wanna cook?",
  "What do you wanna learn?",
  "What do you wanna see?"
 ],
 "7": [
  "How was your day?",
  "How was the class?",
  "How was the concert?",
  "How was your vacation?",
  "How was the food?",
  "How was your interview?",
  "How do you feel about the news?",
  "How do you feel about moving?",
  "How do you feel about the change?",
  "How do you feel about your job?",
  "How do you feel about the decision?",
  "How do you feel about the weather?",
  "How long does it take to cook rice?",
  "How long does it take to get to school?",
  "How long does it take to read this?",
  "How long does it take to download it?",
  "How long does it take to walk there?",
  "How long does it take to fix it?",
  "How can I help?",
  "How can I improve?",
  "How can I sign up?",
  "How can I cancel?",
  "How can I contact you?",
  "How can I register?"
 ],
 "9": [
  "I'm heading to the gym.",
  "I'm heading to work.",
  "I'm heading to the airport.",
  "I'm heading downtown.",
  "I'm heading to the park.",
  "I'm heading to the office.",
  "You can come, if you want to.",
  "You can ask, if you want to.",
  "You can stay, if you want to.",
  "You can try it, if you want to.",
  "You can borrow it, if you want to.",
  "Let me know, if you're free.",
  "Let me know, if you need anything.",
  "Let me know, if it works.",
  "Let me know, if you change your mind.",
  "Let me know, if you're late.",
  "I'm down.",
  "Sure.",
  "Why not?",
  "Sounds good.",
  "Let's do it."
 ],
 "10": [
  "I got a new phone.",
  "I got a job.",
  "I got a cold.",
  "I got a puppy.",
  "I got a raise.",
  "I got a message.",
  "I got tickets.",
  "I got a package.",
  "I get nervous when I speak English.",
  "I get excited when I speak English.",
  "I get shy when I speak English.",
  "I get confused when I speak English.",
  "I get tired when I speak English.",
  "I get happy when I speak English.",
  "Try this ramen, bro!",
  "Try this drink, bro!",
  "Try this app, bro!",
  "Try this game, bro!",
  "Try this pizza, bro!",
  "Try this coffee, bro!",
  "I'm tryna focus.",
  "I'm tryna save money.",
  "I'm tryna learn guitar.",
  "I'm tryna get fit.",
  "I'm tryna sleep early.",
  "I'm tryna finish this."
 ],
 "3": [
  "Awesome!",
  "No worries.",
  "Sounds good.",
  "Same to you.",
  "Take care.",
  "See ya!",
  "Long time no see.",
  "How've you been?",
  "Not much, you?",
  "I'm doing okay.",
  "Can't complain.",
  "Pretty tired, honestly.",
  "So far so good.",
  "Nice to see you.",
  "What's new?",
  "Nothing much.",
  "Good to see you!",
  "Catch you later."
 ],
 "11": [
  "No cap.",
  "That's fire.",
  "Bet.",
  "Facts.",
  "It's lit.",
  "That's sick!",
  "Deadass.",
  "For real?",
  "My bad.",
  "It slaps.",
  "That's rough, buddy.",
  "Say less.",
  "We good.",
  "Chill out.",
  "That's wild.",
  "No way, bro.",
  "I'm dead 💀",
  "Lowkey agree."
 ]
};
