// AUTO-GENERATED from dish_ja.csv (build_ja.py). 日本語はゲート経由でのみ表示する。
const JA = {
 "i wanna be a teacher": "先生になりたい。",
 "im gonna be a teacher": "先生になるつもりだ。",
 "i gotta be a teacher": "先生にならなきゃ。",
 "i am a teacher": "私は先生だ。",
 "i wanna be a firefighter": "消防士になりたい。",
 "i wanna be your boyfriend": "君の彼氏になりたい。",
 "i wanna be confident": "自信を持ちたい。",
 "i wanna be smart": "賢くなりたい。",
 "i wanna do it": "やりたい。",
 "i wanna change the clothes": "服を着替えたい。",
 "i wanna go to america": "アメリカに行きたい。",
 "i wanna drink coffee": "コーヒーが飲みたい。",
 "i wanna hit someone": "誰かを殴りたい。",
 "im gonna be a firefighter": "消防士になるつもりだ。",
 "im gonna be your boyfriend": "君の彼氏になるつもりだ。",
 "im gonna be confident": "自信を持つつもりだ。",
 "im gonna be smart": "賢くなるつもりだ。",
 "im gonna do it": "やるつもりだ。",
 "im gonna change the clothes": "服を着替えるつもりだ。",
 "im gonna go to america": "アメリカに行くつもりだ。",
 "im gonna drink coffee": "コーヒーを飲むつもりだ。",
 "im gonna hit someone": "誰かを殴るつもりだ。",
 "i gotta be a firefighter": "消防士にならなきゃ。",
 "i gotta be your boyfriend": "君の彼氏にならなきゃ。",
 "i gotta be confident": "自信を持たなきゃ。",
 "i gotta be smart": "賢くならなきゃ。",
 "i gotta do it": "やらなきゃ。",
 "i gotta change the clothes": "着替えなきゃ。",
 "i gotta go to america": "アメリカに行かなきゃ。",
 "i gotta drink coffee": "コーヒーを飲まなきゃ。",
 "i gotta hit someone": "誰かを殴らなきゃ。",
 "how do i say apple in japanese": "「apple」って日本語で何て言うの？",
 "whats the difference between a and b": "AとBの違いは何？",
 "could you explain that one more time": "もう一回説明してもらえますか？",
 "how do you use this word": "この単語ってどう使うの？",
 "how do i say thank you in japanese": "「Thank you」って日本語で何て言うの？",
 "how do i say castle in japanese": "「castle」って日本語で何て言うの？",
 "how do i say netherlands in japanese": "「Netherlands」って日本語で何て言うの？",
 "how do i say im nervous in japanese": "「I'm nervous」って日本語で何て言うの？",
 "how do i say detective in japanese": "「Detective」って日本語で何て言うの？",
 "whats the difference between apples and pears": "りんごと梨の違いは何？",
 "whats the difference between novels and manga": "小説と漫画の違いは何？",
 "whats the difference between ocean and stream": "海と小川の違いは何？",
 "whats the difference between eating and drinking": "食べることと飲むことの違いは何？",
 "whats the difference between boy and girl": "男の子と女の子の違いは何？",
 "could you explain the homework one more time": "宿題をもう一回説明してもらえますか？",
 "could you explain the next activity one more time": "次のアクティビティをもう一回説明してもらえますか？",
 "could you explain this grammar rule one more time": "この文法ルールをもう一回説明してもらえますか？",
 "could you explain idiom one more time": "イディオムをもう一回説明してもらえますか？",
 "could you explain slang one more time": "スラングをもう一回説明してもらえますか？",
 "how do you use actually": "「actually」ってどう使うの？",
 "how do you use basically": "「basically」ってどう使うの？",
 "how do you use instead": "「instead」ってどう使うの？",
 "how do you use stuff": "「stuff」ってどう使うの？",
 "how do you use kind of (kinda)": "「kind of（kinda）」ってどう使うの？",
 "a: how are you b: pretty good": "A: 調子どう？ B: かなりいいよ。",
 "a: hows it going b: not bad": "A: 元気してる？ B: 悪くないよ。",
 "a: whats up b: not bad": "A: よっ、調子は？ B: 悪くないよ。",
 "a: i got a girlfriend b: for real": "A: 彼女できた！ B: マジで？",
 "great": "最高！",
 "im not feeling good": "あんまり調子よくない…",
 "pretty good": "かなりいいよ",
 "im nervous": "緊張してる",
 "good thanks": "うん、元気だよ。",
 "not bad": "悪くないよ",
 "im good": "元気だよ",
 "im doing great": "すごく元気だよ",
 "so-so": "まあまあ",
 "sup": "よっ？",
 "just the usual": "いつも通りかな",
 "hey": "やあ",
 "not much": "特に何も",
 "hows it going": "調子どう？",
 "for real": "マジで？",
 "nah its okay bro": "いや大丈夫だよ。",
 "sure": "もちろん。",
 "sweet": "いいね",
 "got it": "了解",
 "yeah maybe": "うん、たぶん",
 "oh yeah": "へえ",
 "uh-huh": "うんうん",
 "right": "だよね",
 "exactly": "まさに",
 "cool": "いいね",
 "yeah": "うん",
 "not really": "そうでもない",
 "what": "え？",
 "okay": "オッケー",
 "maybe": "たぶん",
 "thats cap": "それ嘘でしょ",
 "i see": "なるほど",
 "could be": "かもね",
 "same here": "こっちも同じ",
 "and then": "それで？",
 "i know right": "だよね！",
 "absolutely": "もちろん",
 "of course": "もちろん",
 "no way": "ありえない",
 "about what": "何について？",
 "a: i failed the exam b: nah its okay bro": "A: 試験落ちた！ B: いや大丈夫だよ。",
 "a: do you wanna join us b: sure": "A: 一緒に来る？ B: もちろん！",
 "a: were gonna go to the beach tomorrow b: sweet": "A: 明日ビーチ行くんだ。 B: いいね！",
 "a: did you get it b: got it": "A: 分かった？ B: 了解！",
 "a: are you coming tomorrow b: yeah maybe": "A: 明日来る？ B: うん、たぶん！",
 "a: this movie is really good b: oh yeah": "A: この映画めっちゃいいよ。 B: お～いいね！",
 "a: i went to tokyo yesterday b: uh-huh": "A: 昨日東京行ったんだ。 B: うんうん。",
 "a: english is easy b: right": "A: 英語って簡単だよね。 B: だよね。",
 "a: you know japanese are so shy b: exactly": "A: 日本人ってすごくシャイだよね。 B: まさに。",
 "i wanna be an entrepreneur": "起業家になりたい。",
 "im gonna be an entrepreneur": "起業家になるつもりだ。",
 "i gotta be an entrepreneur": "起業家にならなきゃ。",
 "i think thats more expensive": "そっちの方が高いと思う。",
 "i guess thats more expensive": "そっちの方が高いんじゃないかな。",
 "that sounds more expensive": "そっちの方が高そうだね。",
 "i would like to order the expensive one": "高い方を注文したいです。",
 "i think you are so smart": "君はすごく賢いと思う。",
 "i think i gotta go": "もう行かなきゃだと思う。",
 "i think im gonna leave here in 3 minutes": "あと3分でここを出ると思う。",
 "i think this one is better": "こっちの方がいいと思う。",
 "i guess you are so smart": "君はすごく賢いんじゃないかな。",
 "i guess i gotta go": "もう行かなきゃかな。",
 "i guess im gonna leave here in 3 minutes": "あと3分でここを出るかな。",
 "i guess this one is better": "こっちの方がいいんじゃないかな。",
 "that sounds famous": "有名そうだね。",
 "that sounds good": "良さそうだね。",
 "that sounds perfect": "完璧だね。",
 "that sounds bad": "それはまずそうだね。",
 "that sounds like shit": "それ最悪っぽいね。",
 "i would like to go to the bathroom": "トイレに行きたいです。",
 "i would like to get a ticket": "チケットを買いたいです。",
 "i would like to go there": "そこに行きたいです。",
 "i would like to order this one": "これを注文したいです。",
 "i would like to try this jacket": "このジャケットを試着したいです。",
 "a: we need a deposit first b: what do you mean by deposit": "A: まず頭金が必要です。 B: 「deposit」ってどういう意味？",
 "a: i cant find my phone b: what happened to your phone": "A: スマホが見つからない。 B: スマホどうしたの？",
 "a: this email looks serious b: what should i do about it": "A: このメール、深刻そう。 B: どうすればいい？",
 "a: im free tonight b: what do you wanna do": "A: 今夜ヒマなんだ。 B: 何したい？",
 "what do you mean by deposit": "「deposit」ってどういう意味？",
 "what do you mean by deadline": "「deadline」ってどういう意味？",
 "what do you mean by refund": "「refund」ってどういう意味？",
 "what do you mean by reservation": "「reservation」ってどういう意味？",
 "what do you mean by later": "「later」ってどういう意味？",
 "what happened to your phone": "スマホどうしたの？",
 "what happened to the plan": "あの計画どうなったの？",
 "what happened to the app": "あのアプリどうなったの？",
 "what happened to your bag": "カバンどうしたの？",
 "what happened to the meeting": "あの会議どうなったの？",
 "what should i do about this email": "このメール、どうすればいい？",
 "what should i do about my reservation": "予約、どうすればいい？",
 "what should i do about the deadline": "締め切り、どうすればいい？",
 "what should i do about this problem": "この問題、どうすればいい？",
 "what should i do about this form": "このフォーム、どうすればいい？",
 "what do you wanna eat": "何食べたい？",
 "what do you wanna buy": "何買いたい？",
 "what do you wanna do": "何したい？",
 "what do you wanna try": "何を試したい？",
 "what do you wanna watch": "何見たい？",
 "a: i went to kyoto yesterday b: how was your trip": "A: 昨日京都に行ったんだ。 B: 旅行どうだった？",
 "a: we may switch to online classes b: how do you feel about that": "A: オンライン授業に切り替えるかも。 B: それについてどう思う？",
 "a: i usually go there by train b: how long does it take to get there": "A: いつも電車で行くよ。 B: そこまでどのくらいかかる？",
 "a: i want to join your class b: how can i sign up": "A: あなたのクラスに参加したい。 B: どうやって申し込めばいい？",
 "how was your trip": "旅行どうだった？",
 "how was the movie": "映画どうだった？",
 "how was your test": "テストどうだった？",
 "how was the meeting": "会議どうだった？",
 "how was your weekend": "週末どうだった？",
 "how do you feel about this idea": "このアイデアについてどう思う？",
 "how do you feel about the plan": "その計画についてどう思う？",
 "how do you feel about online classes": "オンライン授業についてどう思う？",
 "how do you feel about the restaurant": "そのレストランについてどう思う？",
 "how do you feel about the new app": "その新しいアプリについてどう思う？",
 "how long does it take to get there": "そこまでどのくらいかかる？",
 "how long does it take to finish this": "これを終わらせるのにどのくらいかかる？",
 "how long does it take to make dinner": "夕飯を作るのにどのくらいかかる？",
 "how long does it take to charge it": "充電するのにどのくらいかかる？",
 "how long does it take to learn this": "これを覚えるのにどのくらいかかる？",
 "how can i join": "どうやって参加すればいい？",
 "how can i fix this": "どうやってこれを直せばいい？",
 "how can i change it": "どうやってこれを変えればいい？",
 "how can i pay": "どうやって払えばいい？",
 "how can i start": "どうやって始めればいい？",
 "im heading to the station": "駅に向かってるよ。",
 "you can join us if you want to": "よかったら一緒に来ていいよ。",
 "let me know if you have questions": "質問があったら教えてね。",
 "im down": "乗った！",
 "im heading home": "家に向かってるよ。",
 "im heading to the school": "学校に向かってるよ。",
 "im heading to the museum": "美術館に向かってるよ。",
 "im heading back soon": "もうすぐ戻るよ。",
 "you can try it if you want to": "よかったら試していいよ。",
 "you dont have to go if you dont want to": "行きたくなかったら行かなくていいよ。",
 "you dont have to answer if you dont want to": "答えたくなかったら答えなくていいよ。",
 "let me know if you need help": "助けが必要なら教えてね。",
 "let me know if youre not sure": "分からなかったら教えてね。",
 "let me know if you need a break": "休憩が必要なら教えてね。",
 "ofc": "もちろん！",
 "why not": "いいね、やろう！",
 "i got a ticket": "チケット取れた！",
 "i get nervous when i speak english": "英語を話すと緊張する。",
 "i got it = i understand / i got this = leave it to me / i got a schedule = i had a schedule": "「I got it」＝分かった／「I got this!」＝任せて！／「I got a schedule」＝予定があった",
 "try this food bro": "これ食べてみなよ！",
 "im tryna speak english": "英語を話そうとしてるんだ。",
 "i got a haircut": "髪切った。",
 "i got a switch2": "Switch2買った。",
 "i got first place": "1位取った。",
 "i got a girlfriend": "彼女できた。",
 "i got a rare t-shirt": "レアなTシャツ手に入れた。",
 "i get excited when i speak english": "英語を話すとワクワクする。",
 "i get shy when i speak english": "英語を話すと恥ずかしくなる。",
 "i get confused when i speak english": "英語を話すと混乱する。",
 "i get tired when i speak english": "英語を話すと疲れる。",
 "try this burger bro": "このバーガー食べてみなよ！",
 "try this coke bro": "このコーラ飲んでみなよ！",
 "try this app bro": "このアプリ使ってみなよ！",
 "try this game bro": "このゲームやってみなよ！",
 "try this restaurant bro": "この店行ってみなよ！",
 "im tryna say something": "何か言おうとしてるんだ。",
 "im tryna learn spanish": "スペイン語を学ぼうとしてるんだ。",
 "im tryna go to tokyo": "東京に行こうとしてるんだ。",
 "im tryna sing this song": "この歌を歌おうとしてるんだ。",
 "im tryna show my picture": "自分の写真を見せようとしてるんだ。",
 "awesome": "最高／すごい",
 "bro": "兄弟／お前（親しい呼びかけ）",
 "basically": "要するに／ぶっちゃけ",
 "wtf": "は？／マジかよ",
 "shit": "クソッ／やべぇ",
 "thats awesome": "それ最高！",
 "you alright bro": "大丈夫か？",
 "basically its good": "ぶっちゃけ、いい感じ",
 "wtf are you talking about": "何言ってんの？",
 "oh shit": "うわ、やべぇ",
 "yo this is bussin": "やば、これうますぎ",
 "lets grab some food": "なんか食べに行こう",
 "this is literally the best coffee ever": "これマジで人生で一番うまいコーヒー",
 "damn it": "くそっ！",
 "that was f**king good": "あれマジでやばかった",
 "yep": "うん",
 "nope are we done": "いや、もう終わり？",
 "im gonna hang out with my friend": "友達と遊ぶんだ",
 "dont worry i got it": "心配すんな、任せて",
 "absolutely not": "絶対やだ！",
 "i gave her a gift": "彼女にプレゼントをあげた。",
 "choose whatever book you like": "好きな本を何でも選んで。",
 "how do i say receipt in english": "「receipt」って英語で何て言うの？",
 "basically its good / wtf are you talking about": "ぶっちゃけ、いい感じ。／何言ってんの？"
};

function norm(s){ return s.toLowerCase().replace(/[.,!?"'`’“”]/g,'').replace(/\s+/g,' ').trim(); }
export function jaFor(en){ return JA[norm(en)] || ''; }
export const JA_COUNT = Object.keys(JA).length;
